> ### **Assignment 2 - Numpy Array Operations** 
>


Write a short introduction about Numpy and list the chosen functions. 

function1 = np.append 

function2 = np.average

function3 = np.arange

function4 = np.squeeze

function5 = np.vstack




In [44]:
import numpy as np

## Function 1 - np.append
np.append function add elements to the end of an array provided that the dimensions of the elements should be same.

In [45]:
# Example 1 - working (change this)
arr1 = [1, 2, 1, 25, 26]
np.append(arr1, [24, 23, 15])


array([ 1,  2,  1, 25, 26, 24, 23, 15])

We can put lists as an element inside the array, then append it with the expected lists or any element regardless of their size.



In [46]:
# Example 2 - working
arr2 = [[2, 4, 5], [6, 7, 8]]
np.append(arr2, [10, 12])
np.append(arr2, [10, 12, 13, 14])

array([ 2,  4,  5,  6,  7,  8, 10, 12, 13, 14])

When axis is specified, arrays must have the same shape.

In [47]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = [[2, 4, 5], [6, 7, 8]]
np.append(arr3, [14, 15, 16], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Some closing comments about when to use this function.

In [ ]:
# Fix
arr3 = [[2, 4, 5], [6, 7, 8]]
np.append(arr3, [[14, 15, 16], [12, 15, 16]], axis = 0)

array([[ 2,  4,  5],
       [ 6,  7,  8],
       [14, 15, 16],
       [12, 15, 16]])

In arr3, index 0 has 2 dimensions, while the element to be appended has 1 dimension, thus breaks down. To fix this, the element to be appended should have 2 dimensions as well.

## Function 2 - np.average

Add some explanations

In [ ]:
# Example 1 - working
arr=[[3,4,5],[6,7,8]]
np.average(arr)

5.5

Explanation about example

In [ ]:
arr1=[[5,4,6],[8,9,7],[5,8,9],[7,8,9]]
np.average(arr1)

7.083333333333333

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
np.average(arr1,[1,2,3,4], axis=0)

TypeError: _average_dispatcher() got multiple values for argument 'axis'

Explanation about example (why it breaks and how to fix it)

In np.average we cannot give the array inside the function we must give only the variable name inside the function if not it will show an error. 

In [ ]:
array=[9,8,7],[9,10,65]
np.average(array)

18.0

Some closing comments about when to use this function.

## Function 3 - np.arange

Add some explanations

In [ ]:
# Example 1 - working
np.arange(3,7)

array([3, 4, 5, 6])

Explanation about example

In [ ]:
# Example 2 - working
np.arange(3,7,2)

array([3, 5])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
np.arange(3,7,int)

TypeError: unsupported operand type(s) for /: 'int' and 'type'

Explanation about example (why it breaks and how to fix it)

np.arrange syntax is (start,stop,increment,dtype) so we must have the same syntax if not it will show error.

In [ ]:
np.arange(3,7,2,int)

array([3, 5])

Some closing comments about when to use this function.

## Function 4 - np.squeeze

Add some explanations

In [ ]:
# Example 1 - working
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [ ]:
np.squeeze(x,axis=0).shape

(3, 1)

Explanation about example

In [48]:
# Example 2 - working
x1 = np.array([[[0], [1], [2]]])
x1.shape


(1, 3, 1)

In [51]:
np.squeeze(x1,axis=2).shape

(1, 3)

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
x11 = np.array([[[0], [1], [2]]])
x1.shape

(1, 3, 1)

In [ ]:
np.squeeze(x11,axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

Explanation about example (why it breaks and how to fix it)

row and dimesions are equal to one but here column is so that is not equal to one . so here display the error.

Some closing comments about when to use this function.

## Function 5 - np.vstack

Add some explanations

In [54]:
# Example 1 - working
x = np.array([6,7,8])
y = np.array([10,11,14])
np.vstack((x,y))

array([[ 6,  7,  8],
       [10, 11, 14]])

Explanation about example

vstack is join the array in vertical order in single array.


In [55]:
# Example 2 - working
x = np.array([[67], [56], [57]])
y = np.array([[15], [17], [19]])
np.vstack((x,y))

array([[67],
       [56],
       [57],
       [15],
       [17],
       [19]])

Explanation about example

In [58]:
# Example 3 - breaking (to illustrate when it breaks)
???
x=np.array([3,4,5])
y=np.array([3,5])
np.vstack((x,y))

Object `?` not found.


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

Explanation about example (why it breaks and how to fix it)

x and y must have same array size otherwise its shows error.

Some closing comments about when to use this function.